#!/usr/bin/env bun
/**
 * App Bundler Studio CLI -- Standalone Binary Compiler & macOS .app Packager
 * Leverages Bun's native single-file executable compiler (bun build --compile)
 */
import { SimpleCLI } from '../src/index.ts';
import * as fs from 'node:fs';
import * as path from 'node:path';

const app = SimpleCLI.newApp('bundler-cli', '1.0.0')
  .setDescription('Native Single-File Executable Compiler & macOS .app Packager');

app.addFlagString('entry', 'e', './index.ts', 'Entrypoint TypeScript file to compile');
app.addFlagString('name', 'n', 'bun_app', 'Output executable/app name');
app.addFlagString('target', 't', 'bun-darwin-arm64', 'Target: bun-darwin-arm64, bun-darwin-x64, bun-linux-x64, bun-windows-x64');
app.addFlagString('out', 'o', './dist', 'Output directory');
app.addFlagBool('minify', 'm', true, 'Minify generated bytecode bundle');
app.addFlagBool('app', 'a', false, 'Package into standalone macOS .app bundle');
app.addFlagString('id', 'i', 'com.enterprise.app', 'macOS Bundle ID');

if (!app.parseCli()) process.exit(0);

const entryPath = path.resolve(process.cwd(), app.getFlagString('entry'));
const appName = app.getFlagString('name');
const targetArch = app.getFlagString('target');
const outDir = path.resolve(process.cwd(), app.getFlagString('out'));
const minify = app.getFlagBool('minify');
const packageApp = app.getFlagBool('app');
const bundleId = app.getFlagString('id');

app.banner('App Bundler Studio CLI', 'v1.0.0 - Native Single-File Executable Compiler');

if (!fs.existsSync(entryPath)) {
  app.error(`Entry file not found: ${entryPath}`);
  process.exit(1);
}

fs.mkdirSync(outDir, { recursive: true });

async function compileBinary(): Promise<string> {
  const binaryOutput = path.join(outDir, appName);
  app.info(`Compiling standalone binary for target [${targetArch}]...`);
  app.info(`Source: ${entryPath} -> Output: ${binaryOutput}`);

  const args = ['build', '--compile', `--target=${targetArch}`];
  if (minify) args.push('--minify');
  args.push(`--outfile=${binaryOutput}`, entryPath);

  const start = performance.now();
  const proc = Bun.spawn(['bun', ...args], {
    stdout: 'inherit',
    stderr: 'inherit',
  });

  const code = await proc.exited;
  const elapsed = (performance.now() - start).toFixed(2);

  if (code !== 0) {
    throw new Error(`Compiler exited with code ${code}`);
  }

  let sizeMb = 'unknown';
  if (fs.existsSync(binaryOutput)) {
    const st = fs.statSync(binaryOutput);
    sizeMb = (st.size / (1024 * 1024)).toFixed(2) + ' MB';
  }

  app.success(`Compiled binary in ${elapsed}ms | Size: ${sizeMb}`);
  return binaryOutput;
}

function buildMacApp(binPath: string) {
  const bundlePath = path.join(outDir, `${appName}.app`);
  const macosDir = path.join(bundlePath, 'Contents', 'MacOS');
  const resDir = path.join(bundlePath, 'Contents', 'Resources');

  app.info(`Packaging into macOS bundle: ${bundlePath}...`);
  fs.mkdirSync(macosDir, { recursive: true });
  fs.mkdirSync(resDir, { recursive: true });

  const targetBin = path.join(macosDir, appName);
  fs.copyFileSync(binPath, targetBin);
  fs.chmodSync(targetBin, 0o755);

  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleExecutable</key>
  <string>${appName}</string>
  <key>CFBundleIdentifier</key>
  <string>${bundleId}</string>
  <key>CFBundleName</key>
  <string>${appName}</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>1.0.0</string>
  <key>NSHighResolutionCapable</key>
  <true/>
</dict>
</plist>`;

  fs.writeFileSync(path.join(bundlePath, 'Contents', 'Info.plist'), plist, 'utf8');
  app.success(`Successfully generated macOS bundle: ${bundlePath}`);
}

async function main() {
  try {
    const bin = await compileBinary();
    if (packageApp && process.platform === 'darwin') {
      buildMacApp(bin);
    }
  } catch (err: any) {
    app.error(`Compilation failed: ${err.message}`);
    process.exit(1);
  }
}

main();
